version: '3.8'
services:
  api:
    build: ./api
    container_name: api
    ports:
      - '8080:8080'
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: secret
      DB_NAME: cdc
    volumes:
      - type: bind
        source: ./api
        target: /app
    depends_on:
      - mysql
    networks:
      - cdc-net
networks:
  cdc-net:
    name: cdc-net
