version: "2.2"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - type: bind
        source: ./data/druid/postgres
        target: /var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=FoolishPassword
      - POSTGRES_USER=druid
      - POSTGRES_DB=druid
    networks:
      - cdc-net

  zookeeper:
    container_name: zookeeper
    image: zookeeper:3.5.10
    ports:
      - "2181:2181"
    environment:
      - ZOO_MY_ID=1
    networks:
      - cdc-net

  coordinator:
    image: apache/druid:33.0.0
    container_name: coordinator
    volumes:
      - type: bind
        source: ./data/druid/shared
        target: /opt/shared
      - type: bind
        source: ./data/druid/coordinator_var
        target: /opt/druid/var
    depends_on:
      - zookeeper
      - postgres
    ports:
      - "8081:8081"
    command:
      - coordinator
    env_file:
      - ./environment
    networks:
      - cdc-net

  broker:
    image: apache/druid:33.0.0
    container_name: broker
    volumes:
      - type: bind
        source: ./data/druid/broker_var
        target: /opt/druid/var
    depends_on:
      - zookeeper
      - postgres
      - coordinator
    ports:
      - "8082:8082"
    command:
      - broker
    env_file:
      - ./environment
    networks:
      - cdc-net

  historical:
    image: apache/druid:33.0.0
    container_name: historical
    volumes:
      - type: bind
        source: ./data/druid/shared
        target: /opt/shared
      - type: bind
        source: ./data/druid/historical_var
        target: /opt/druid/var
    depends_on:
      - zookeeper
      - postgres
      - coordinator
    ports:
      - "8083:8083"
    command:
      - historical
    env_file:
      - ./environment
    networks:
      - cdc-net

  middlemanager:
    image: apache/druid:33.0.0
    container_name: middlemanager
    volumes:
      - type: bind
        source: ./data/druid/shared
        target: /opt/shared
      - type: bind
        source: ./data/druid/middle_var
        target: /opt/druid/var
    depends_on:
      - zookeeper
      - postgres
      - coordinator
    ports:
      - "8091:8091"
      - "8100-8105:8100-8105"
    command:
      - middleManager
    env_file:
      - ./environment
    networks:
      - cdc-net

  router:
    image: apache/druid:33.0.0
    container_name: router
    volumes:
      - type: bind
        source: ./data/druid/router_var
        target: /opt/druid/var
    depends_on:
      - zookeeper
      - postgres
      - coordinator
    ports:
      - "8888:8888"
    command:
      - router
    env_file:
      - ./environment
    networks:
      - cdc-net

networks:
  cdc-net:
    name: cdc-net
